config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "tasks#index"
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  
  resources :tasks
  resources :users, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    validates :status, presence: true, length: { maximum: 10 }
    validates :content, presence: true, length: { maximum: 255 }
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true, length: { maximum: 255 }
    validates :email, presence: true, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: { case_sensitive: false }
    has_secure_password
    has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    include SessionsHelper
    
    private
        def require_user_logged_in
            unless logged_in?
                redirect_to login_url
            end
        end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = "ログインに成功しました。"
      redirect_to root_url
    else
      flash.now[:danger] = "ログインに失敗しました。"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "ログアウトしました。"
    redirect_to login_url
  end
  
  private
    def login(email, password)
      @user = User.find_by(email: email)
      if @user && @user.authenticate(password)
        session[:user_id] = @user.id
        return true
      else
        return false
      end
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :require_user_logged_in
    before_action :correct_user, only: [:show, :edit, :update, :destroy]
    
    def index
        @tasks = Task.all
    end
    
    def show
        
    end
    
    def new
        @task = current_user.tasks.build
    end
    
    def create
        @task = current_user.tasks.build(strong_params)
        if @task.save
            flash[:success] = "タスクが作成されました。"
            redirect_to @task
        else
            flash.now[:danger] = "タスクが作成されませんでした。"
            render :new
        end
    end
    
    def edit
        
    end
    
    def update
        if @task.update(strong_params)
            flash[:success] = "タスクは正常に変更されました。"
            redirect_to @task
        else
            flash[:danger] = "タスクは変更されませんでした。"
            render :edit
        end
    end
    
    def destroy
        @task.destroy
        flash[:success] = "タスクは削除されました"
        redirect_to tasks_url
    end
    
    private
        def strong_params
            params.require(:task).permit(:content, :status)
        end
        
        def correct_user
            @task = current_user.tasks.find_by(id: params[:id])
            unless @task
                flash[:danger] = "無効な操作です。"
                redirect_to tasks_url
            end
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "ユーザーを新規作成しました。"
      redirect_to login_url
    else 
      flash.now[:danger] = "ユーザー登録に失敗しました。"
      render :new
    end
  end
  
  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    
    def logged_in?
        !!current_user
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
    <div>
        <ul>
            <% model.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/layouts/_flash_message.html.erb
<% flash.each do |message_type, message| %>
    <%= message %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasklist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <%= render "layouts/flash_message" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |f| %>
    <% if task.errors.any? %>
        <div class="error-detail">
            <ul>
                <% task.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <%= f.label :content, "タスク" %>
    <%= f.text_field :content %>
    
    <%= f.label :status, "ステータス" %>
    <%= f.text_field :status %>
    
    <%= f.submit "投稿" %>
<% end %>

app/views/tasks/edit.html.erb
<h1>編集ページ</h1>
<%= render "form", task: @task %>
<%= link_to "一覧に戻る", tasks_path %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>
<% if logged_in? %>
    <p><%= current_user.name %> がログイン中</p>
<% end %>
<ul>
     
    <% @tasks.each do |task| %>
        <% if current_user == task.user %>
            <li><%= link_to task.id, task %>: <%= task.content %>, <%= task.status %></li>
        <% end %>
    <% end %>
</ul>
<%= link_to "新規投稿", new_task_path %>
<%= link_to "Logout", logout_path, method: :delete %>

app/views/tasks/new.html.erb
<h1>タスク新規投稿</h1>
<%= render "form", task: @task %>

<%= link_to "一覧に戻る", tasks_path %>

app/views/tasks/show.html.erb
<h1>ID: <%= @task.id %> の詳細ページ</h1>
<p>Content: <%= @task.content %></p>
<p>Status: <%= @task.status %></p>
<%= link_to "一覧に戻る", tasks_path %>
<% if current_user == @task.user %>
    <%= link_to "タスクを編集する", edit_task_path %>
    <%= link_to "タスクを削除する", @task, method: :delete, data: { confirm: "本当に削除しても大丈夫ですか？" } %>
<% end %>

app/views/users/new.html.erb
<div>
    <h1>Sign up</h1>
</div>
<div>
    <%= form_with(model: @user, local: true) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
        <div>
            <%= f.label :name, "Name" %>
            <%= f.text_field :name %>
        </div>
        
        <div>
            <%= f.label :email, "Email" %>
            <%= f.text_field :email %>
        </div>
        
        <div>
            <%= f.label :password, "Password" %>
            <%= f.password_field :password %>
        </div>
        
        <div>
            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation %>
        </div>
        <%= f.submit "Sign up" %>
    <% end %>
    <%= link_to "Log in", login_path %>
</div>